### PR TITLE
add setOptions method for Slick.DataView

### PR DESCRIPTION
**Pull request by bcherny**

### CODE REVIEW

**Comment by bcherny** [comment]
@SimplGy @albertywu can you take a look?

**Comment by SimplGy** [comment]
Do you have some explanation around this, like what problem you're fixing?

**Comment by bcherny** [comment]
see https://github.com/coatue/gandalf/pull/5287/files#diff-b0ec5daf5f94ec380764e0e831071417R13

**Comment by bcherny** [comment]
i need the ability to set a groupItemMetadataProvider at runtime, after the dataview has been initialized.

**Comment by SimplGy** [comment]
I see. Ok, I'd probably extend the defaults, and have DataView's constructor use setOptions so they go through the same code path. https://github.com/SimplGy/SlickGrid/blob/master/slick.dataview.js#L80

SlickGrid's options sometimes were order sensitive (eg: if you set them after init, they don't take), but I don't see anything like that on DataView.

**Comment by bcherny** [comment]
> I see. Ok, I'd probably extend the defaults, and have DataView's constructor use setOptions so they go through the same code path.

that would overwrite options that were previously set via setOptions, no?

**Comment by SimplGy** [comment]
Not if you [extend](https://github.com/SimplGy/SlickGrid/blob/master/slick.grid.js#L1684) it. It's stuck in my head because slickgrid does a bunch of reset stuff along with setting options. Doesn't really matter here I guess, do what you want. :+1:

**Comment by bcherny** [comment]
ah, gotcha. just pushed - better?

**Pull request merged**
