### PR TITLE
add option to skip paging in grid

### PR DESCRIPTION
**Pull request by albertywu**
(TJ needs to get permissions to the repo... committing this in his behalf)

### CODE REVIEW

**Comment by bcherny** [comment]
Can you give some context for this? What do you mean by paging?

Also, you should set a default value for this option in the defaults config at the top of slick.grid.js, and document it in the readme.

**Comment by albertywu** [comment]
When the current active cell is at the edge of the viewport (either first or last row in viewport), pressing down / up on the keyboard normally "pages" to an entirely new set of rows. We want an option to disable paging, and reveal one row at a time instead.

**Comment by bcherny** [comment]
Slickgrid controls moving the selection on key press right? Why and how would the consumer pass this option in? Would it reset the option on every selection change depending on the cursor position?

Let's talk it over tomorrow.

**Comment by bcherny** [comment]
:+1:

**Pull request merged**
