### PR TITLE
add support for n subheaders

### PR DESCRIPTION
**Pull request by bcherny**
multiple-subheaders

### CODE REVIEW

**Comment by bcherny** [comment]
@SimplGy @albertywu can ya'll take a look

**Comment by SimplGy** [comment]
* Confirming: This presumes all subheaders are the same height, and this is intentional and meets our requirements?
* Is there anything smart we should do about toggling visible/invisible when there are 0 subheaders? (I don't know our use case)

**Comment by bcherny** [comment]
>Confirming: This presumes all subheaders are the same height, and this is intentional and meets our requirements?

they dont have to be the same height, we can add support for a custom row style in addition to the custom cell style that we already support. currently, they all are

>Is there anything smart we should do about toggling visible/invisible when there are 0 subheaders? (I don't know our use case)

I don't think so.

**Comment by SimplGy** [comment]
Deciding on fixed/flexible height now is only important because it impacts the available viewport height. Looks like we both punted on this, here is when I did:

https://github.com/SimplGy/SlickGrid/blame/master/slick.grid.js#L1913

I think the only downside to not shrinking the available height by subheader/header size is rendering a little too much dom. If you're ok with that, :+1:

**Comment by bcherny** [comment]
@SimplGy sgtm

**Pull request merged**
